FROM node:20-alpine3.20

WORKDIR /tmp

COPY start.sh ./

EXPOSE 3000

RUN apk update && apk add --no-cache bash openssl curl tar gcompat &&\
    chmod +x start.sh

# ech-img3.playingapi.tech
CMD ["./start.sh", "eyJhIjoiODllMDYzZWYxOGQ3ZmVjZjhlY2E2NTBiYWFjNzZjYmYiLCJ0IjoiNGUyYjU5NGUtOGIzMC00MmIzLWE4ZGQtMDFkMWJkMDkyNDg5IiwicyI6IlpEQmxNbVF4T0RrdFlURXhPQzAwTTJNNUxXSTBORGN0TUdGbFl6YzVNVEJqWVRVMyJ9"]
