FROM node:20-alpine3.20

WORKDIR /tmp

COPY start.sh ./

EXPOSE 3000

RUN apk update && apk add --no-cache bash openssl curl tar gcompat &&\
    chmod +x start.sh

# ech-img2.playingapi.tech
CMD ["./start.sh", "eyJhIjoiODllMDYzZWYxOGQ3ZmVjZjhlY2E2NTBiYWFjNzZjYmYiLCJ0IjoiZDg5ZjYwZGYtYzdiNy00MTVmLThhZTYtNzE2ZTg4NmM4YTczIiwicyI6IllqQTRZMkV4WkRndFltRTJaQzAwTVdFMkxXSTFaVEF0WW1WaE16TmxZVEZrWlRFNSJ9"]
